// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RCM.API.Infrastucture.Persistance;

#nullable disable

namespace RCM.API.Infrastructure.Persistance.Migrations
{
    [DbContext(typeof(RCMDbContext))]
    [Migration("20260316121039_IntialCreate")]
    partial class IntialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RCM.API.Featuers.RequestForJobPost.JobRequestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.PrimitiveCollection<string>("PositionIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VacantPositionCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("JobRequest");
                });
#pragma warning restore 612, 618
        }
    }
}
